# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: postprocessing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'postprocessing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14postprocessing.proto\x12\x0epostprocessing\"M\n\x12PostProcessRequest\x12\x13\n\x0braw_content\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x12\n\nredact_pii\x18\x03 \x01(\x08\"j\n\x13PostProcessResponse\x12\x1a\n\x12structured_content\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2o\n\x15PostProcessingService\x12V\n\x0bPostProcess\x12\".postprocessing.PostProcessRequest\x1a#.postprocessing.PostProcessResponseB2Z0github.com/user/idep/shared/proto/postprocessingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'postprocessing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/user/idep/shared/proto/postprocessing'
  _globals['_POSTPROCESSREQUEST']._serialized_start=40
  _globals['_POSTPROCESSREQUEST']._serialized_end=117
  _globals['_POSTPROCESSRESPONSE']._serialized_start=119
  _globals['_POSTPROCESSRESPONSE']._serialized_end=225
  _globals['_POSTPROCESSINGSERVICE']._serialized_start=227
  _globals['_POSTPROCESSINGSERVICE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
