package postprocessing

import (
	"context"

	"google.golang.org/grpc"
)

// --- Types ---

type PostProcessRequest struct {
	RawContent string
	JobId      string
	RedactPii  bool
}

type PostProcessResponse struct {
	StructuredContent string
	ConfidenceScore   float32
	Status            string
	Error             string
}

// --- Server Interface ---

type PostProcessingServiceServer interface {
	PostProcess(context.Context, *PostProcessRequest) (*PostProcessResponse, error)
	mustEmbedUnimplementedPostProcessingServiceServer()
}

type UnimplementedPostProcessingServiceServer struct{}

func (UnimplementedPostProcessingServiceServer) PostProcess(context.Context, *PostProcessRequest) (*PostProcessResponse, error) {
	return nil, nil
}
func (UnimplementedPostProcessingServiceServer) mustEmbedUnimplementedPostProcessingServiceServer() {}

func RegisterPostProcessingServiceServer(s grpc.ServiceRegistrar, srv PostProcessingServiceServer) {
	// In production, this would be generated by protoc-gen-go-grpc
}

// --- Client Interface ---

type PostProcessingServiceClient interface {
	PostProcess(ctx context.Context, in *PostProcessRequest, opts ...grpc.CallOption) (*PostProcessResponse, error)
}

type postProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostProcessingServiceClient(cc grpc.ClientConnInterface) PostProcessingServiceClient {
	return &postProcessingServiceClient{cc}
}

func (c *postProcessingServiceClient) PostProcess(ctx context.Context, in *PostProcessRequest, opts ...grpc.CallOption) (*PostProcessResponse, error) {
	// In production, this would use cc.Invoke() with the generated method descriptor
	return &PostProcessResponse{
		StructuredContent: in.RawContent,
		ConfidenceScore:   0.95,
		Status:            "success",
	}, nil
}
