package preprocessing

import (
	"context"

	"google.golang.org/grpc"
)

// --- Types ---

type PreprocessRequest struct {
	FilePath string
	JobId    string
	Deskew   bool
	Denoise  bool
}

type PreprocessResponse struct {
	ImagePaths []string
	Status     string
	Error      string
}

// --- Server Interface ---

type PreprocessingServiceServer interface {
	Preprocess(context.Context, *PreprocessRequest) (*PreprocessResponse, error)
	mustEmbedUnimplementedPreprocessingServiceServer()
}

type UnimplementedPreprocessingServiceServer struct{}

func (UnimplementedPreprocessingServiceServer) Preprocess(context.Context, *PreprocessRequest) (*PreprocessResponse, error) {
	return nil, nil
}
func (UnimplementedPreprocessingServiceServer) mustEmbedUnimplementedPreprocessingServiceServer() {}

func RegisterPreprocessingServiceServer(s grpc.ServiceRegistrar, srv PreprocessingServiceServer) {
	// In production, this would be generated by protoc-gen-go-grpc
}

// --- Client Interface ---

type PreprocessingServiceClient interface {
	Preprocess(ctx context.Context, in *PreprocessRequest, opts ...grpc.CallOption) (*PreprocessResponse, error)
}

type preprocessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreprocessingServiceClient(cc grpc.ClientConnInterface) PreprocessingServiceClient {
	return &preprocessingServiceClient{cc}
}

func (c *preprocessingServiceClient) Preprocess(ctx context.Context, in *PreprocessRequest, opts ...grpc.CallOption) (*PreprocessResponse, error) {
	// In production, this would use cc.Invoke() with the generated method descriptor
	// For local dev, this is a simulation path
	return &PreprocessResponse{
		ImagePaths: []string{"simulated_page_1.png"},
		Status:     "success",
	}, nil
}
